---
title: "Results"
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
execute:
  eval: false
---

---

# Results

---

## Identification of ZWHQD active ingredients

---

## Identification of candidate ZWHQD target genes

---

## Identification of potential HFrEF genes

---

## Acquirement of ZWHQD-HFrEF hub genes

---

## Functional enrichment analysis and expression in different groups of GZSYZM-RA hub gene set

---

## Immune filtration analysis based on CIBERSORT algorithm

---

## Annotation of cell subpopulations in scRNA-seq datasets using clustering and dimensionality reduction analysis

---

## Calculation of the AUCell score for specific cell subpopulation

---

## Identification of GZSYZM-RA core genes with causal association using Mendelian randomization analysis

---

## Diagnostic value assessment of GZSYZM-RA core genes in rheumatoid arthritis

---

## Gene set enrichment analysis of CASP8

---

## Molecular docking of CASP8 with five constituents of GZSYZM

---


---

<table class="nav-table" width="100%">
  <tr>
    <td align="left">
      [Home](index.qmd) | [About](about.qmd) | [Methods](methods.qmd)
    </td>
    <td align="right">
      [Start Analysis](analysis/Part_1_Data_acquisition_and_preprocessing.qmd)
    </td>
  </tr>
</table>