---
  title: "09. Immune Infiltration Profiling"
format: 
  html:
  toc: true
number-sections: true
---
  
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

## Load Package
```{r}
library(GSVA)
library(GSEABase)
library(msigdbr)
library(pheatmap) 
library(tidyverse) 
library(rstatix) 
library(corrplot) 
library(ggpubr) 
library(ggsci)
library(ggsignif)
library(ggplot2)
library(IOBR)
library(openxlsx)
library(Seurat)
```

## Step 1: FPKM & group

```{r}
rm(list = ls())
load("../data/processed/geo/gse57338.RData")

group <- pheno %>% 
  rownames_to_column("Sample") %>%
  dplyr::select(Sample,group) %>%
  dplyr::rename(Group = group)


fpkm <- 2^expr_filt - 1
fpkm[fpkm < 0] <- 0
```

## Step 2: deconvo_tme
```{r}
# MCPcounter
res_mcp   <- deconvo_tme(eset = fpkm, method = "mcpcounter")

# xCell
res_xcell <- deconvo_tme(eset = fpkm, method = "xcell")

# quanTIseq
res_quant <- deconvo_tme(eset = fpkm, method = "quantiseq")

# EPIC
res_epic  <- deconvo_tme(eset = fpkm, method = "epic")

save(res_mcp, res_xcell, res_quant, res_epic, file = "../data/processed/ime/res.RData")
```

## Step 3: Extracting data
```{r}
mcp_mat <- res_mcp %>% column_to_rownames("ID")
colnames(mcp_mat) <- gsub("_MCPcounter", "", names(mcp_mat))

df_all <- mcp_mat %>% 
  rownames_to_column("Sample") %>%
  left_join(group,by="Sample")

# Stacking data
df_stack <- df_all %>%
  pivot_longer(cols=-c(Sample,Group), names_to="Cell", values_to="Abundance") %>% 
  group_by(Group, Cell) %>% 
  summarise(Mean = mean(Abundance), .groups = "drop")

pvals <- apply(df_all[,2:(ncol(df_all)-1)], 2, function(x) {
  wilcox.test(x ~ df_all$Group)$p.value
})

sig_cells <- names(pvals)[pvals < 0.05]

df_plot <- df_all[,c("Sample","Group",sig_cells)] %>%
  pivot_longer(cols=-c(Sample,Group), names_to="Cell", values_to="Abundance")

group_levels <- unique(df_plot$Group)
comparison_list <- list(c(group_levels[1], group_levels[2]))
```

## Step 4: Figure 5A~E
```{r}
# Figure A: Differential immune cell box plot
df_clean <- df_plot %>%
  group_by(Cell) %>%
  mutate(
    Q1 = quantile(Abundance, 0.25),
    Q3 = quantile(Abundance, 0.75),
    IQR = Q3 - Q1,
    upper_limit = Q3 + 1.5 * IQR
  ) %>%
  filter(Abundance <= upper_limit) %>% 
  ungroup()

pA <- ggplot(df_clean, aes(x = Group, y = Abundance, fill = Group)) +
  geom_boxplot(outlier.shape = NA, width = 0.6) +
  stat_compare_means(
    method = "wilcox.test",
    aes(label = paste0("p = ", ..p.format..)),
    # parse = TRUE,  
    size = 2.5,                 
    vjust = 0.6,               
    hjust = 0.5,
    label.x.npc = 0.5,          
    hide.ns = FALSE      
  ) +
  
  facet_wrap(~Cell, ncol = 4, scales = "free_y") +

  scale_fill_jco() +
  
  theme_bw(base_size = 10, base_family = "serif") +
  theme(
    axis.text.x = element_text(size = 7),
    strip.background = element_rect(fill = "gray90"),
    strip.text = element_text(face = "bold", size = 7),
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 6),
    legend.position = "bottom"
  ) +
  labs(x = NULL, y = "Abundance")

ggsave("../figures/main/nFigure_5A.pdf",pA,width=14, height=10, units="cm",dpi=300)

# Figure B: Stacking
pB <- ggplot(df_stack, 
       aes(x = Group,                
           y = Mean, 
           fill = Cell)) +
  geom_col(position = "fill", width = 0.6) +
  scale_y_continuous(labels = scales::percent_format()) +
  ggsci::scale_fill_jco() +
  labs(x = NULL, y = "Proportion", fill = "Cell") +
  theme_bw(base_size = 8, base_family = "serif") +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7),
    axis.title = element_text(size = 8),
    legend.title = element_text(size = 7),  
    legend.text  = element_text(size = 6), 
    legend.key.size = unit(0.25, "cm"), 
    legend.spacing.x = unit(0.15, "cm"),
    legend.spacing.y = unit(0.05, "cm"),
    legend.margin = margin(2,2,2,2), 
    legend.box.margin = margin(0,0,0,0),
    legend.position = "right",  
    legend.direction = "vertical"
  )

ggsave("../figures/main/nFigure_5B.pdf", pB, width=7, height=5, units="cm", dpi=300)

# Figure C: Bar chart of differential immune cell sorting
df_mean <- df_plot %>% 
  group_by(Cell, Group) %>%
  summarise(Mean = mean(Abundance), .groups = "drop") %>%
  pivot_wider(names_from = Group, values_from = Mean)

# FC = HF / HC
df_mean$FoldChange <- df_mean[[2]] / df_mean[[3]]
df_mean <- df_mean %>% arrange(FoldChange)  

pC <- ggplot(df_mean, 
             aes(x = FoldChange, 
                 y = reorder(Cell, FoldChange), 
                 fill = Cell)) + 
  geom_col(width = 0.65) +
  geom_vline(xintercept = 1, color = "red", linetype = "dashed", linewidth = 0.5) +
  ggsci::scale_fill_aaas() +   
  labs(x = "Fold Change (HF/HC)", y = "") +
  theme_bw(base_size = 7, base_family = "serif") + 
  scale_x_continuous(
    breaks = seq(0, 1.2, 0.2),
    expand = c(0, 0) 
  ) + 
  theme(
    axis.text.y = element_text(size = 7),
    axis.text.x = element_text(size = 7),
    axis.title.x = element_text(size = 7),
    axis.ticks.y = element_blank(),
    plot.margin = margin(t = 1, r = 1, b = 1, l = -2, unit = "mm"),
    legend.position = "none"
  )

ggsave("../figures/main/nFigure_5C.pdf", pC, width=7, height=5, units="cm", dpi=300)

# Figure D: Heat map of immune cell correlation
library(corrplot)
imm_exp  <- mcp_mat[, sig_cells] %>%
  rownames_to_column("Sample") %>%
  left_join(group,by="Sample") %>%
  column_to_rownames("Sample") %>%
  dplyr::filter(Group=="HF") %>%
  dplyr::select(-Group)

cor_mat_cell <- cor(imm_exp, method = "spearman")

pdf("../figures/main/nFigure_5D.pdf", width=7, height=5)
corrplot(
  cor_mat_cell,
  method = "color",
  type = "upper",   
  diag = FALSE,    
  order = "original",
  col = colorRampPalette(c("navy","white","red3"))(100),
  tl.cex = 0.7,      
  cl.cex = 0.6,
  tl.srt = 45,
  tl.col = "black",
  mar = c(1, 0, 1, 0),    
  cl.offset = 0.2,        
  t.pos = "left",
  addCoef.col = "black",
  number.cex = 0.6,
)
dev.off()

# Figure E: Hub genes-immune cell correlation heatmap
load("../data/processed/network/08_hub_genes.Rdata")

hub_exp  <- fpkm[hub_genes, ] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Sample") %>%
  left_join(group,by="Sample") %>%
  column_to_rownames("Sample") %>%
  dplyr::filter(Group=="HF") %>%
  dplyr::select(-Group)

cor_mat <- cor(imm_exp, hub_exp, method="spearman")
p_mat <- matrix(NA, nrow = ncol(imm_exp), ncol = ncol(hub_exp),
                dimnames = list(colnames(imm_exp), colnames(hub_exp)))

for(i in 1:ncol(imm_exp)){
  for(j in 1:ncol(hub_exp)){
    p_mat[i,j] <- cor.test(imm_exp[,i], hub_exp[,j], method = "spearman")$p.value
  }
}

library(ggplot2)
library(ggsci)
library(reshape2)

cor_long <- melt(cor_mat)
p_long <- melt(p_mat)
cor_long$p <- p_long$value
colnames(cor_long) <- c("Cell","HubGene","Corr","Pvalue")

pE <- ggplot(cor_long, aes(x = HubGene, y = Cell)) +
  geom_tile(aes(fill = Corr), color = "gray90", size = 0.1) +
  scale_fill_gradient2(low = "#2166AC", mid = "white", high = "#B2182B",midpoint = 0, limits = c(-1,1)) +
  theme_minimal() +
  theme(
    text = element_text(family = "serif", size = 7),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 6,margin = margin(t = 0.5, unit = "mm")),
    axis.text.y = element_text(size = 6,margin = margin(r = 0.5, unit = "mm")),
    axis.title = element_blank(),
    legend.position = "right",
    legend.key.size = unit(0.15, "cm"),  
    legend.title = element_text(size = 5),
    legend.text  = element_text(size = 4), 
    legend.box.spacing = unit(0.01, "cm"), 
    legend.margin = margin(0,0,0,0),       
    plot.margin = margin(0.5,0.5,0.5,0.5, "mm"),
    panel.grid = element_blank()
  ) +
  labs(fill = "Correlation")

ggsave("../figures/main/nFigure_5E.pdf", pE, width = 7, height = 5, units = "cm", dpi = 300)
```

## Figure 5

```{r}
library(magick)

total_width_cm <- 14        
dpi <- 300                    
px_per_cm <- dpi / 2.54     
total_width_px <- round(total_width_cm * px_per_cm) 

ratios_row1 <- c(1)
ratios_row2 <- c(1, 1) 
ratios_row3 <- c(1, 1) 

width_row1_left  <- round(total_width_px * ratios_row1[1] / sum(ratios_row1))
width_row2_left  <- round(total_width_px * ratios_row2[1] / sum(ratios_row2))
width_row2_right <- round(total_width_px * ratios_row2[2] / sum(ratios_row2))

width_row3_left  <- round(total_width_px * ratios_row3[1] / sum(ratios_row3))
width_row3_right <- round(total_width_px * ratios_row3[2] / sum(ratios_row3))

ratio <- c(width_row1_left,width_row2_left,width_row2_right,width_row3_left,width_row3_right)

files <- c(
  "../figures/main/nFigure_5A.pdf",
  "../figures/main/nFigure_5B.pdf",
  "../figures/main/nFigure_5C.pdf",
  "../figures/main/nFigure_5D.pdf",
  "../figures/main/nFigure_5E.pdf"
)

labels <- c("A", "B", "C", "D", "E")

label_size <- 12   

pdfs <- list()
for (i in seq_along(files)) {
  img <- image_read_pdf(files[i], density = 300)
  img <- image_resize(img,ratio[i])
  img <- image_annotate(img, labels[i], 
                        gravity = "northwest",  
                        location = "+10+10",    
                        size = label_size,     
                        weight = 700,    
                        color = "black")
  pdfs[[i]] <- img
}

row1 <- image_append(c(pdfs[[1]]), stack = FALSE)
row2 <- image_append(c(pdfs[[2]], pdfs[[3]]), stack = FALSE)
row3 <- image_append(c(pdfs[[4]], pdfs[[5]]), stack = FALSE)

combined <- image_append(c(row1, row2, row3), stack = TRUE)


image_write(combined, "../figures/main/nFigure_5.pdf", format = "pdf")
image_write(combined, "../figures/main/nFigure_5.png", format = "png", density = dpi)

```