---
title: "07. GO and KEGG"
format: 
  html:
    toc: true
    number-sections: true
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# Loading Packages
```{r}
# 加载包
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)
```

# candidate_genes
```{r}
rm(list = ls())

# candidate_genes <- c(
#   "MGST1","SNCA","ABCG2","CD14","SOCS3","STAT3","ALOX5","CDKN1A","CTSC","NQO1",
#   "SERPINE1","FOS","BLM","CA14","PDE5A","FGF1","MME","ANPEP","PLA2G2A","ALOX5AP",
#   "CCR1","MAPK10","JAK2","EDNRB","PNP","HTR4","PDE8B","SLC2A1","EPHX2","CD38",
#   "ADAMTS4","NAMPT","HIF1A","MAP2K1","GHR","MT2A","BCL2L1","PTPN1","LDHA","KCNH2",
#   "MET","CCND1","CDK2","CASP1","PIM1","EPHA3","HDAC9","ACVRL1","RIPK2"
# )

load("../data/processed/network/01_herb_disease_genes.RData")


entrez_ids <- bitr(candidate_genes_df$Gene, 
                   fromType = "SYMBOL",      
                   toType = "ENTREZID",    
                   OrgDb = org.Hs.eg.db)
```

# GO (BP+CC+MF） 
```{r}
go <- enrichGO(
  gene = candidate_genes_df$Gene,
  OrgDb = org.Hs.eg.db,
  keyType = "SYMBOL",
  ont = "ALL",
  pAdjustMethod = "fdr",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.20
)
```

# KEGG
```{r}
kk <- enrichKEGG(
  gene = entrez_ids$ENTREZID,
  organism = "hsa",         
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.20
)
```

# Figure 3C. GO (BP/CC/MF)
```{r}
pdf("../figures/main/nFigure_3C.pdf", width = 10, height = 9)
dotplot(go, split = "ONTOLOGY", showCategory = 5) + 
  facet_grid(ONTOLOGY ~ ., scale = "free") +
  theme_bw() 
# +
#   ggtitle("GO Enrichment")
dev.off()
```

# Figure 3D. KEGG
```{r}
pdf("../figures/main/nFigure_3D.pdf", width = 10, height = 9)
dotplot(kk, showCategory = 15) + 
  theme_bw()
dev.off()
```

# Table S4. GO + KEGG
```{r}
save(go,kk,file = "../data/processed/functional/enrich_new.RData")

write.xlsx(
  list(
    GO = go,
    KEGG = kk
  ),
  "../tables/Table_S4.xlsx"
)
```