---
title: "MR + coloc"
format: 
  html:
    toc: true
    number-sections: true
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# 贝叶斯共定位
## Loading Packages
```{r}
library(coloc)
library(data.table)
library(dplyr)
library(stringr)
library(org.Hs.eg.db)
library(AnnotationDbi)
```

## Loading data
### Hub genes
```{r}
load("../data/processed/network/08_hub_genes.RData")
rm(hub_genes_tbl,top_degree,top_mcc,top_mnc)
```

### GTEx v8 Heart_Left_Ventricle eQTL
```{r}
eQTL <- fread("../data/raw/opengwas/GTEx_Analysis_v8_eQTL/Heart_Left_Ventricle.v8.signif_variant_gene_pairs.txt.gz")

# eGenes: Used for rapid filtering
eGenes <- fread("../data/raw/opengwas/GTEx_Analysis_v8_eQTL/Heart_Left_Ventricle.v8.egenes.txt.gz")

gene2ensg <- eGenes %>%
  dplyr::select(gene_id,gene_name) %>%
  dplyr::filter(gene_name %in% hub_genes) %>%
  mutate(gene_id = sub("\\..*", "",gene_id)) %>%
  arrange(gene_name)

eQTL <- eQTL %>%
  mutate(gene_id = sub("\\..*", "",gene_id))

for (i in nrow(hub_genes_tbl)) {
    print(gene2ensg$gene_name[i])
    eqtl_sub <- eQTL %>% filter(gene_id == gene2ensg$gene_id[i])
    print(nrow(eqtl_sub))
}
```

### HERMES2 GWAS: HERMES2_Pheno5_MTAG
```{r}
gwas <- fread("../data/raw/opengwas/HERMES2_GWAS_DCM_EUR/FORMAT-METAL_Pheno5-MTAG_EUR.tsv.gz")
```

## 核心函数：单个基因 coloc 分析
```{r}
run_coloc_single_gene <- function(gene_name, ensg_id) {
  
  cat("正在分析：", gene_name, " | ", ensg_id, "\n")
  
  # ====================== 1. 提取该基因的 eQTL ======================
  eqtl_sub <- eQTL %>% filter(gene_id == ensg_id)
  
  if(nrow(eqtl_sub) == 0) {
    cat(gene_name, "无 eQTL，跳过\n")
    return(NULL)
  }
  
  # 整理成 coloc 格式
  eqtl_coloc <- list(
    pvalues = eqtl_sub$pval_nominal,
    beta = eqtl_sub$slope,
    varbeta = eqtl_sub$slope_se^2,
    snp = eqtl_sub$variant_id,
    MAF = eqtl_sub$maf,
    type = "quant"
  )
  
  # ====================== 2. 提取 GWAS 对应 SNP ======================
  gwas_sub <- gwas %>% filter(`#key` %in% eqtl_sub$variant_id)
  
  if(nrow(gwas_sub) == 0) {
    cat(gene_name, "GWAS 无重叠位点，跳过\n")
    return(NULL)
  }
  
  # GWAS 整理成 coloc 格式
  gwas_coloc <- list(
    pvalues = gwas_sub$pval,
    beta = gwas_sub$A1_beta,
    varbeta = gwas_sub$se^2,
    snp = gwas_sub$`#key`,
    MAF = gwas_sub$A1_freq,
    type = "cc",         # 病例对照
    s = 6001 / (6001+28704) # 病例数/总数
  )
  
  # ====================== 3. 运行贝叶斯共定位 ======================
  res <- coloc.abf(dataset1 = gwas_coloc,
                   dataset2 = eqtl_coloc)
  
  # 输出结果
  out <- data.frame(
    gene = gene_name,
    ensg = ensg_id,
    n_snps = res$summary[1],
    PP.H0 = res$summary[2],
    PP.H1 = res$summary[3],
    PP.H2 = res$summary[4],
    PP.H3 = res$summary[5],
    PP.H4 = res$summary[6]
  )
  
  return(out)
}
```

## 批量运行 
```{R}
coloc_results <- list()

for (i in 1:nrow(gene2ensg)) {
  g <- gene2ensg$gene[i]
  e <- gene2ensg$ensg[i]
  coloc_results[[i]] <- run_coloc_single_gene(g, e)
}

# 合并成表格
final <- bind_rows(coloc_results)

# 查看结果
final %>% arrange(desc(PP.H4))

# 保存
fwrite(final, "coloc_results_18hub_genes.csv")
```
