---
title: "new_network"
format: html
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# Identification of Candidate Targets

## Load Packages
```{r}
library(ggvenn)
library(tidyverse)
library(openxlsx)
library(ggsci)
```

## Candidate Genes
```{r}
rm(list = ls())

load("../data/processed/geo/gse57338_degs_results.RData")
load("../data/processed/tcm/14_compound_target_final.RData")
load("../data/processed/geo/gse57338_hub_genes_wgcna.RData")

deg_genes <- rownames(deg_sig) 
herb_targets <- unique(compound_target_final$Symbol)

# disease_genes: intersecting DEGs and WGCNA
disease_genes <- intersect(deg_genes,hub_genes_wgcna$Gene)

# candidate_genes: intersecting herb_targets and disease_genes
# candidate_genes <-intersect(herb_targets, disease_genes)

############
candidate_genes1 <-intersect(herb_targets, deg_genes)
candidate_genes2 <-intersect(herb_targets, hub_genes_wgcna$Gene)

candidate_genes <- unique(union(candidate_genes1,candidate_genes2))
#############



herb_targets_df <- data.frame(Gene = herb_targets) %>%
  arrange(Gene)

deg_genes_df <- data.frame(Gene = deg_genes) %>%
  arrange(Gene)

wgcna_genes_df <- hub_genes_wgcna %>%
  arrange(Gene)

disease_genes_df <- data.frame(Gene = disease_genes) %>%
  arrange(Gene)

candidate_genes_df <- data.frame(Gene = candidate_genes) %>%
  arrange(Gene)

#############
hit_core <- compound_target_final %>%
    dplyr::filter(Symbol %in% candidate_genes_df$Gene) %>%
  arrange(Herb.Name.Pinyin,Symbol)

unique(hit_core$Herb.Name.Pinyin)

key_compounds <- hit_core[,c("Herb.Name.Pinyin", "Compound.Name","Symbol")]

############

gene_list <- list(
  DEGs = deg_genes,
  `Herb targets` = herb_targets,
  `WGCNA Genes` = wgcna_candidates_genes$Gene
)

p <- ggvenn(
  gene_list,
  fill_color = pal_aaas()(4),
  stroke_color = "white",
  stroke_size = 1,
  set_name_size = 5,
  text_size = 5,
  text_color = "white",
  show_percentage = FALSE
) +
  theme(plot.title = element_text(hjust = 0.5, size=10))

# save
ggsave("../figures/main/Figure_3A.pdf", p, width=6, height=6, dpi=300)
ggsave("../figures/main/Figure_3A.png", p, width=6, height=6, dpi=300)


save(herb_targets_df, deg_genes_df, wgcna_genes_df,disease_genes_df, candidate_genes_df, file = "../data/processed/network/01_herb_disease_genes.RData")

write.xlsx(
  list(
    HerbTargets = herb_targets_df,
    DEGs = deg_genes_df,
    WGCNAGenes = wgcna_genes_df,
    DiseaseGenes = disease_genes_df,
    CandidateGenes = candidate_genes_df
  ),
  "../tables/candidate_genes.xlsx"
)

deg_candidate <- deg_all[rownames(deg_all) %in% candidate_genes, ]
 
deg_candidate$regulation <- ifelse(
  deg_candidate$log2FoldChange >= lfc, "Up",
  ifelse(deg_candidate$log2FoldChange <= -lfc, "Down", "NS")
)

deg_candidate$Gene <- rownames(deg_candidate)

up_genes <- deg_candidate$Gene[deg_candidate$regulation == "Up"]
down_genes <- deg_candidate$Gene[deg_candidate$regulation == "Down"]

cat("Up genes: ", length(up_genes), "\n")
print(up_genes)

cat("\nDown genes: ", length(down_genes), "\n")
print(down_genes)
```

## GO + KEGG
```{r}
# 加载包
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)

entrez_ids <- bitr(candidate_genes, 
                   fromType = "SYMBOL",      # 输入类型为基因符号
                   toType = "ENTREZID",      # 输出类型为 Entrez ID
                   OrgDb = org.Hs.eg.db)

# candidate_genes <- c(
#   "MGST1","SNCA","ABCG2","CD14","SOCS3","STAT3","ALOX5","CDKN1A","CTSC","NQO1",
#   "SERPINE1","FOS","BLM","CA14","PDE5A","FGF1","MME","ANPEP","PLA2G2A","ALOX5AP",
#   "CCR1","MAPK10","JAK2","EDNRB","PNP","HTR4","PDE8B","SLC2A1","EPHX2","CD38",
#   "ADAMTS4","NAMPT","HIF1A","MAP2K1","GHR","MT2A","BCL2L1","PTPN1","LDHA","KCNH2",
#   "MET","CCND1","CDK2","CASP1","PIM1","EPHA3","HDAC9","ACVRL1","RIPK2"
# )

# ======================== GO 富集（BP+CC+MF） ========================
go <- enrichGO(
  gene = candidate_genes,
  OrgDb = org.Hs.eg.db,
  keyType = "SYMBOL",
  ont = "ALL",
  pAdjustMethod = "fdr",
  qvalueCutoff = 0.05
)

# GO 分面条形图（BP/CC/MF 自动分开）
pdf("../figures/main/GO_Barplot.pdf", width = 12, height = 9)
dotplot(go, split = "ONTOLOGY", showCategory = 6) + 
  facet_grid(ONTOLOGY ~ ., scale = "free") +
  theme_bw() +
  ggtitle("GO Enrichment")
dev.off()

# ======================== KEGG 富集 ========================
kk <- enrichKEGG(
  gene = entrez_ids$ENTREZID,
  organism = "hsa",          # 人类
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.10
)

# KEGG 气泡图
pdf("../figures/main/KEGG_Bubble.pdf", width = 10, height = 7)
dotplot(kk, showCategory = 15, title = "KEGG Pathway") + 
  theme_bw()
dev.off()

# ======================== 输出富集表格 ========================
write.csv(as.data.frame(go), "../tables/GO_Enrichment_Result.csv", row.names = F)
write.csv(as.data.frame(kk), "../tables/KEGG_Enrichment_Result.csv", row.names = F)

```


## HIT


## PPI


## Hub Genes