---
title: "new_geo"
format: 
  html:
    toc: true
    number-sections: true
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# GEO datasets

## Load Packages
```{r}
library(tidyverse)
library(data.table)
library(openxlsx)
library(patchwork)
library(ggrepel)
library(vegan)
library(GEOquery)
library(limma)
library(DESeq2)
library(edgeR)
library(sva)
library(org.Hs.eg.db)
if (!require("TxDb.Hsapiens.UCSC.hg38.knownGene")) {
  BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
}
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
```

## GSE57338
```{r,warning=FALSE}
rm(list=ls())

raw_dir <- "../data/raw/geo/GSE57338"
if (!dir.exists(raw_dir)) dir.create(raw_dir, recursive = TRUE)

Sys.setlocale("LC_ALL", "C")
gse57338 <- getGEO("GSE57338", destdir = raw_dir, getGPL = TRUE, AnnotGPL = F)
Sys.setlocale("LC_ALL", "")

gse57338_pheno_raw <- pData(gse120895[[1]])
gse57338_exprs_raw <- exprs(gse120895[[1]])

save(
  gse57338_pheno_raw,
  gse57338_exprs_raw,
  file = "../data/raw/geo/gse57338_raw.RData"
)
```

## GSE5406
```{r,warning=FALSE}
rm(list=ls())

raw_dir <- "../data/raw/geo/GSE5406"
if (!dir.exists(raw_dir)) dir.create(raw_dir, recursive = TRUE)

Sys.setlocale("LC_ALL", "C")
gse5406 <- getGEO("GSE5406", destdir = raw_dir, getGPL = TRUE, AnnotGPL = F)
Sys.setlocale("LC_ALL", "")

gse5406_pheno_raw <- pData(gse5406[[1]])
gse5406_exprs_raw <- exprs(gse5406[[1]])

save(
  gse5406_pheno_raw,
  gse5406_exprs_raw,
  file = "../data/raw/geo/gse5406_raw.RData"
)
```
